# Puerto donde corre el servidor
server.port=8080

spring.datasource.url=jdbc:h2:file:./autoelite_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# (clave aquí cuando no se use la de SwtService.java)
# Clave secreta HS256 [mínimo 256 bits / 32 caracteres]
jwt.secret=InsertarAquíClaveOmegaSecretaOmegaLargaEpicaQueContieneAlMenos256Bits
